# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-20 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_goods', '0004_bookinfo_publish_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(max_length=60, primary_key=True, serialize=False, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isPay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='总价')),
                ('address', models.CharField(default='', max_length=120, verbose_name='地址')),
                ('count', models.IntegerField(default=1, verbose_name='书籍个数')),
                ('pay_status', models.CharField(choices=[('success', '已支付'), ('close', '超时关闭'), ('paying', '待支付')], default='paying', max_length=100, verbose_name='支付状态')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.BookInfo', verbose_name='书籍信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
    ]
