# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_publish', '0002_auto_20181120_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='books',
            new_name='books_id',
        ),
    ]
