# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_publish', '0003_auto_20181121_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='books_id',
            new_name='books',
        ),
    ]
