# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-18 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='公告名')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最新更新时间')),
                ('browers_number', models.IntegerField(default=0, verbose_name='浏览量')),
                ('desc', tinymce.models.HTMLField(verbose_name='简介')),
                ('intro', tinymce.models.HTMLField(verbose_name='介绍')),
            ],
            options={
                'verbose_name': '公告表',
                'verbose_name_plural': '公告表',
            },
        ),
    ]
