# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-14 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='number',
            field=models.IntegerField(default=100, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='picture',
            field=models.ImageField(upload_to='books', verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
    ]
