# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 02:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('df_goods', '0002_auto_20181114_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='share_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分享用户'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='picture',
            field=models.ImageField(upload_to='books', verbose_name='图片'),
        ),
    ]
