# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 03:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0003_auto_20181116_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
    ]
